# Generated by Django 3.2.7 on 2021-12-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20211218_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='img',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
